# =============================  Input  =======================================
fasta: "/path/to/ref.fasta"
refgtf: "/path/to/ref.gtf"
refrna:  "/path/to/ref.fa"


# =============================  Output  ======================================
outdir: "output"
